apiVersion: v1
kind: Service
metadata:
  name: hurace-frontend
  namespace: hurace
spec:
  selector:
    app: hurace
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hurace-frontend
  namespace: hurace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hurace
      tier: frontend
  template:
    metadata:
      labels:
        app: hurace
        tier: frontend
    spec:
      containers:
        - name: hurace-frontend
          image: ammerzon/hurace-frontend:1.0.0
          env:
            - name: API_BASE_URL
              value: "<BACKEND-URL>"
          ports:
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hurace-frontend-ingress
  namespace: hurace
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: hurace-frontend
              servicePort: 80
