/**
 * Hurace API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RaceStatus = 'ready' | 'inProgress' | 'finished';

export const RaceStatus = {
    Ready: 'ready' as RaceStatus,
    InProgress: 'inProgress' as RaceStatus,
    Finished: 'finished' as RaceStatus
};

