/**
 * Hurace API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaceStatus } from './raceStatus';
import { RaceType } from './raceType';
import { Gender } from './gender';
import { Location } from './location';


export interface Race { 
    name?: string | null;
    date?: Date;
    location?: Location | null;
    gender?: Gender;
    raceType?: RaceType;
    description?: string | null;
    website?: string | null;
    pictureUrl?: string | null;
    numberOfSensors?: number;
    completedRuns?: number;
    status?: RaceStatus;
    id?: number;
}

