/**
 * Hurace API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RunStatus = 'ready' | 'completed' | 'inProgress' | 'unfinished' | 'notStarted' | 'disqualified';

export const RunStatus = {
    Ready: 'ready' as RunStatus,
    Completed: 'completed' as RunStatus,
    InProgress: 'inProgress' as RunStatus,
    Unfinished: 'unfinished' as RunStatus,
    NotStarted: 'notStarted' as RunStatus,
    Disqualified: 'disqualified' as RunStatus
};

