/**
 * Hurace API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Country } from './country';
import { Gender } from './gender';


export interface Skier { 
    firstName?: string | null;
    lastName?: string | null;
    birthdate?: Date;
    pictureUrl?: string | null;
    archived?: boolean;
    country?: Country | null;
    gender?: Gender;
    id?: number;
}

